name: SecureOP
author: jeeperscreeper77
version: 1.10
description: Use a password
main: com.PyritePrison.SecureOP.Main
commands:
  op:
    description: Players must know the password to op someone
permissions:
  SecureOP.op:
    default: op
  SecureOP.op
    default: op