name: SecureOP
author: jeeperscreeper77
version: 1.10
description: Use a password
main: club.hardcoreminecraft.javase.secureop.main
commands:
  op:
    description: Players must know the password to op someone
  deop:
    description: Players must know the password to deop someone
permissions:
  SecureOP.op:
    default: op
  SecureOP.deop:
    default: op
  Secureop.receive:
    default: op